plugins: [jekyll-paginate]
paginate: 6
paginate_path: /blog/page:num/
permalink: /:categories/:title/
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"